spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      connection-timeout: 10000
      max-lifetime: 60000
    url: jdbc:mysql://localhost:3307/e-commerce?allowPublicKeyRetrieval=true&useSSL=false
    username: hhplus
    password: hhplus
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop # none, create, create-drop, update, validate
    defer-datasource-initialization: true # 아래 sql init 시점에
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
      # hibernate.dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always # never, always, embedded
      data-locations:
        - classpath:sql/init.sql


management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.1 # 100% 샘플링



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE